Add: Legacy UI test parameter inputs - case 1
This test reflects the current state of play.

Migrating to the pipeline set out in issue #113 will enable this
to be replaced by the more informative text and error location:

error: this attribute takes one argument

         = help: use

 --> tests/ui/has-arguments.rs:3:1
  |
3 | #[trace(a, b)]
  | ^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the attribute macro
    (in Nightly builds, run with -Z macro-backtrace for more info)

Signed-off-by: Mark Van de Vyver <mark@taqtiqa.com>