Add: Legacy UI test parameter inputs (#120)
* Doc: Describe pipeline and test execution

Signed-off-by: Mark Van de Vyver <mark@taqtiqa.com>

* Add: Cargo configuration for UI test suite

Signed-off-by: Mark Van de Vyver <mark@taqtiqa.com>

* Add: Legacy UI test parameter inputs - case 1

This test reflects the current state of play.

Migrating to the pipeline set out in issue #113 will enable this
to be replaced by the more informative text and error location:

error: this attribute takes one argument

         = help: use

 --> tests/ui/has-arguments.rs:3:1
  |
3 | #[trace(a, b)]
  | ^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the attribute macro
    (in Nightly builds, run with -Z macro-backtrace for more info)

Signed-off-by: Mark Van de Vyver <mark@taqtiqa.com>

* Add: Legacy UI test parameter inputs - case 2

Signed-off-by: Mark Van de Vyver <mark@taqtiqa.com>

* Add: Legacy UI test parameter inputs - case 3
Signed-off-by: Mark Van de Vyver <mark@taqtiqa.com>

* Add: Legacy UI test parameter inputs - case 4
Signed-off-by: Mark Van de Vyver <mark@taqtiqa.com>

* Evolve: Legacy UI test parameter inputs

Signed-off-by: Mark Van de Vyver <mark@taqtiqa.com>

* Fix: Legacy UI test parameter input result

Signed-off-by: Mark Van de Vyver <mark@taqtiqa.com>

* Add: Legacy UI test parameter inputs - case 5
Signed-off-by: Mark Van de Vyver <mark@taqtiqa.com>

* Add: Legacy UI test parameter inputs - case 6
Signed-off-by: Mark Van de Vyver <mark@taqtiqa.com>

* Add: Legacy UI test parameter inputs - case 7
Signed-off-by: Mark Van de Vyver <mark@taqtiqa.com>

* Add: Legacy UI test parameter inputs - case 8
Signed-off-by: Mark Van de Vyver <mark@taqtiqa.com>

* Add: Trace macro tests

Signed-off-by: Mark Van de Vyver <mark@taqtiqa.com>

* Add: Legacy UI test parameter inputs - case 9
Signed-off-by: Mark Van de Vyver <mark@taqtiqa.com>

* Add: Legacy UI test parameter inputs - case 10
Signed-off-by: Mark Van de Vyver <mark@taqtiqa.com>

* Add: Legacy UI test parameter inputs - case 11
Signed-off-by: Mark Van de Vyver <mark@taqtiqa.com>

* Add: Legacy UI test parameter inputs - case 12
Signed-off-by: Mark Van de Vyver <mark@taqtiqa.com>